# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anime.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(426, 697)
        self.u_label_title = QtWidgets.QLabel(Dialog)
        self.u_label_title.setGeometry(QtCore.QRect(50, 20, 91, 41))
        self.u_label_title.setObjectName("u_label_title")
        self.u_graghView_picture = ImageView(Dialog)
        self.u_graghView_picture.setGeometry(QtCore.QRect(60, 80, 291, 351))
        self.u_graghView_picture.setObjectName("u_graghView_picture")
        self.u_text_tagInput = QtWidgets.QTextEdit(Dialog)
        self.u_text_tagInput.setGeometry(QtCore.QRect(60, 570, 301, 21))
        self.u_text_tagInput.setObjectName("u_text_tagInput")
        self.u_btn_submit = QtWidgets.QPushButton(Dialog)
        self.u_btn_submit.setGeometry(QtCore.QRect(90, 620, 75, 23))
        self.u_btn_submit.setObjectName("u_btn_submit")
        self.u_pText_tagDesc = QtWidgets.QPlainTextEdit(Dialog)
        self.u_pText_tagDesc.setGeometry(QtCore.QRect(60, 510, 301, 41))
        self.u_pText_tagDesc.setObjectName("u_pText_tagDesc")
        self.u_label_tag = QtWidgets.QLabel(Dialog)
        self.u_label_tag.setGeometry(QtCore.QRect(30, 570, 31, 21))
        self.u_label_tag.setObjectName("u_label_tag")
        self.u_btn_randomGet = QtWidgets.QPushButton(Dialog)
        self.u_btn_randomGet.setGeometry(QtCore.QRect(250, 620, 75, 23))
        self.u_btn_randomGet.setObjectName("u_btn_randomGet")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(110, 460, 181, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.u_radioBtn_noero = QtWidgets.QRadioButton(self.splitter)
        self.u_radioBtn_noero.setObjectName("u_radioBtn_noero")
        self.u_radioBtn_ero = QtWidgets.QRadioButton(self.splitter)
        self.u_radioBtn_ero.setObjectName("u_radioBtn_ero")
        self.u_radioBtn_both = QtWidgets.QRadioButton(self.splitter)
        self.u_radioBtn_both.setObjectName("u_radioBtn_both")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "艺术鉴赏"))
        self.u_label_title.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">艺术鉴赏</span></p></body></html>"))
        self.u_text_tagInput.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.u_btn_submit.setText(_translate("Dialog", "线上获取"))
        self.u_pText_tagDesc.setPlainText(_translate("Dialog", "tag:图片的属性 属性可以有单个和多个\n"
"多个属性之间用空格分开，如：少女 女仆"))
        self.u_label_tag.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">tag</span></p></body></html>"))
        self.u_btn_randomGet.setText(_translate("Dialog", "线下随机"))
        self.u_radioBtn_noero.setText(_translate("Dialog", "非工口"))
        self.u_radioBtn_ero.setText(_translate("Dialog", "工口"))
        self.u_radioBtn_both.setText(_translate("Dialog", "混合"))
from my_utils.ImageView import ImageView
